title: JohnResearch
email: johnresearchs@outlook.com
description: 'Technology, Software, Systems, Security, Data, Engineering, Governance, AIML, Analytics'
baseurl: ''
url: 'https://johnresearches.github.io'
twitter_username: johnresearches
github_username: johnresearches
stackoverflow_username: 3375521/full-array
github_repo: johnresearches.github.io
markdown: kramdown
remote_theme: broccolini/swiss
theme_color: blue
repository: johnresearches/johnresearches.github.io
plugins:
  - jekyll-feed
